### ISSUE TITLE
Cheyenne Web Server

### ISSUE THREAD

**Issue by rlander** [rebolek/lest#20]
I just discovered Lest and I think it's awesome. However, I'm thinking about using Cheyenne on the backend and it runs on Rebol 2. Is there any technical issue that prevents Lest from being ported to Rebol 2? Thanks!

**Comment by rebolek** [comment]
Hi Rodrigo,

thanks! I’m really glad you like Lest. So for your question: Lest uses some PARSE techniques available in R3 only. It also uses map! type, not available in R2. But I think it is possible to backport it to R2, this stuff can be replaced with more code. Unfortunately, I’m not going to do it because of time constrains.
However, what I WILL do, is porting Lest to Red, the language in which future version of Cheyenne will be written.

Hope this helps a bit,
Bolek

**Comment by rlander** [comment]
Thanks! I was thinking about backporting as a learning exercise but you're right, I should probably wait for a stable Red version and help move it forward. Again, thanks for open source Lest!
